version: '3'

volumes:
  dynamodb_data:

services:
  dynamodb:
    image: amazon/dynamodb-local
    user: root
    restart: always
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - dynamodb_data:/home/dynamodblocal/data